### ISSUE TITLE
Subscription verification fails

### ISSUE THREAD

**Issue by nekr0z** [aaronpk/websub.rocks#23]
websub.rocks claims it has subscribed...
![Screenshot_20200504_184454](https://user-images.githubusercontent.com/1515080/80985132-7bd31d00-8e37-11ea-9958-2a23d52a0025.png)

but it looks like it didn't:
![Screenshot_20200504_184514](https://user-images.githubusercontent.com/1515080/80985178-87264880-8e37-11ea-98fe-268d8a0841cb.png)

**Comment by aaronpk** [comment]
Fixed, thanks!

**Comment by nekr0z** [comment]
Still the same behaviour on the hosted version. Not yet updated or another bug?

(Originally published at: https://evgenykuznetsov.org/reactions/2020/22/)

**Comment by aivchen** [comment]
I have the same problem.

**Comment by nekr0z** [comment]
Still the same behaviour on the hosted version. Not yet updated or another bug?

(Originally published at: https://evgenykuznetsov.org/en/reactions/2020/22/)
